### ISSUE TITLE
More formats?

### ISSUE THREAD

**Issue by ghost** [thelostt/ricing#3]
I think it would be kinda cool if the book were available in more formats (for example, LaTeX, HTML, roff, and so on)

If you want, I can hack some scripts together to automate it. Just a thought though :)

**Comment by feroldi** [comment]
Yeah, roff would be a good idea. I only don't know how it would go for stuff like images (because some items talk about X, and surely there will be pictures to show).

Other formats like html or pdf are okay, you all may redistribute this book in whatever form (don't forget the LICENSE when doing so, though).

**Comment by feroldi** [comment]
Closing. Go to #4
