### ISSUE TITLE
[I-new] X Resources

### ISSUE THREAD

**Issue by ghost** [thelostt/ricing#8]
Adding in relevant info about X Resources to file `item2.md`. 
Teach the reader differences between files like `.Xdefaults` and `.xinitrc`, explain the `xrdb` tool, and talk about the simple syntax of the aforementioned dotfiles and what you can do with them.

**Comment by feroldi** [comment]
Okay, I've read your stuff. Here's my initial plan for this item:

1. Explain what [xresources is about](https://stuff.mit.edu/afs/sipb/project/doc/ixresources/xres.html), then it's syntax, caveats and so on.
2. What's the thing with xrdb (it becomes clearer what it is for, after explaining xres) and how to use it (and explain its side effects).
3. Create the files skeleton following the tips from item1.
4. The .xinitrc thing. Let's just mention it in order to load files with xrdb, no need to go further in an unrelated topic.

By the way, don't put ready-to-use things in the book. Don't raise the laziness in the reader, let him craft things and not just copy-paste. You can go into rich details here.

If you think it's time to pull request, then mention¹ this issue in the commit message, and I'll review your content.

¹ "commit message example #8"

**Comment by ghost** [comment]
@thelostt Alright, thanks for the pointers. I'll edit to match and send a PR afterwards.

**Comment by feroldi** [comment]
Reopening for further use.

I'm going to write about this tool: https://github.com/arianon/xrq

**Comment by randomn4me** [comment]
I have a few additions for this section:

1. replaced `riceterm` with an actual program which one can test this on (in this case `urxvt`).
2. Corrected typos

Then I have a question about the display part in this section. Is this really relevant? I never used the display option and am ricing since two years. For me it seems like an overload for a new ricer.

**Comment by feroldi** [comment]
> I have a question about the display part in this section. Is this really relevant?

At the time I was writing, I didn't think much about it and just went with that. Things can change.

**Comment by randomn4me** [comment]
So what do you think about it. You are the owner of this repository.

**Comment by feroldi** [comment]
As I said, things can change. The part about `xrdb` can get stripped to the essential for ricing.
